name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - name: Updating docker compose
        run: |
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start OpenFGA
        run: docker-compose -f hosting/docker-compose.yaml up --wait

      - name: Run tests
        working-directory: ./operator
        run: make test
