controllerManager:
  openFgaUrl: 'http://openfga.default.svc.cluster.local:8080'
  openFgaApiToken: foobar
  manager:
    args:
    - --leader-elect
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: k3d-registry.localhost:12345/openfga-operator
      tag: latest
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
  extraEnvVars: []
    
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
