apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fga-operator.fullname" . }}-authorizationmodel-viewer-role
  labels:
  {{- include "fga-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodels/status
  verbs:
  - get