apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fga-operator.fullname" . }}-deployment-clusterrole
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fga-operator.fullname" . }}-deployment-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "fga-operator.fullname" . }}-controller-manager
  namespace: '{{ .Release.Namespace }}'
roleRef:
  kind: ClusterRole
  name: {{ include "fga-operator.fullname" . }}-deployment-clusterrole
  apiGroup: rbac.authorization.k8s.io
