apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fga-operator.fullname" . }}-manager-role
  labels:
  {{- include "fga-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodelrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodelrequests/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodelrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodels/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodels/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fga-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "fga-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "fga-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "fga-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'