apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fga-operator.fullname" . }}-store-editor-role
  labels:
  {{- include "fga-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - extensions.fga-operator
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.fga-operator
  resources:
  - stores/status
  verbs:
  - get