apiVersion: v2
name: fga-operator
description: |
  A Helm chart for deploying fga-operator on Kubernetes. 
  The operator manages and automates the deployment, 
  scaling, and maintenance of OpenFGA instances.
type: application
version: 0.1.0-9818426264
appVersion: "0.1.0"
