# Configuration for the FGA Operator Controller Manager
controllerManager:
  # URL of the OpenFGA API
  # If openFgaUrlEnvVar is defined, it will be used as the value for the OPENFGA_API_URL environment variable.
  # If openFgaUrlEnvVar is not defined but openFgaUrlFromSecret is defined, the value from the specified secret (key: OPENFGA_API_URL) will be used.
  # openFgaUrlEnvVar: 'http://openfga.default.svc.cluster.local:8080'
  
  # API token for accessing the OpenFGA API using preshared keys.
  # If openFgaApiTokenEnvVar is defined, it will be used as the value for the OPENFGA_API_TOKEN environment variable.
  # If openFgaApiTokenEnvVar is not defined but openFgaApiTokenFromSecret is defined, the value from the specified secret (key: OPENFGA_API_TOKEN) will be used.
  # openFgaApiTokenEnvVar: foobar

  # Secret which contains URL of the OpenFGA API
  # Secret should have key OPENFGA_API_URL
  # If openFgaUrlEnvVar is not defined but openFgaUrlFromSecret is defined, the value from the specified secret (key: OPENFGA_API_URL) will be used.
  # openFgaUrlFromSecret: fgaSecret
  
  # Secret which contains API token for accessing the OpenFGA API using preshared keys.
  # Secret should have key OPENFGA_API_TOKEN
  # If openFgaApiTokenEnvVar is not defined but openFgaApiTokenFromSecret is defined, the value from the specified secret (key: OPENFGA_API_TOKEN) will be used.
  # openFgaApiTokenFromSecret: fgaSecret
  
  manager:
    # Arguments to pass to the controller manager
    args:
    - --leader-elect
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=0
    - --zap-devel=false
    
    # Security context for the controller manager container
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
        
    # Image configuration for the controller manager
    image:
      repository: ghcr.io/3schwartz/fga-operator
      tag: "11408839528"
      
    # Resource requests and limits for the controller manager container
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
        
  # Number of replicas for the controller manager
  replicas: 1
  
  # Service account configuration for the controller manager
  serviceAccount:
    annotations: {}
    
  # Additional environment variables for the controller manager container
  extraEnvVars: []

# Kubernetes cluster domain
kubernetesClusterDomain: cluster.local

# Metrics service configuration
metricsService:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
