# permissions for end users to view authorizationmodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: authorizationmodel-viewer-role
rules:
- apiGroups:
  - extensions.openfga-controller
  resources:
  - authorizationmodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.openfga-controller
  resources:
  - authorizationmodels/status
  verbs:
  - get
