# permissions for end users to view authorizationmodelrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: authorizationmodelrequest-viewer-role
rules:
- apiGroups:
  - extensions.fga-controller
  resources:
  - authorizationmodelrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.fga-controller
  resources:
  - authorizationmodelrequests/status
  verbs:
  - get
