---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - extensions.fga-controller
  resources:
  - authorizationmodelrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.fga-controller
  resources:
  - authorizationmodelrequests/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.fga-controller
  resources:
  - authorizationmodelrequests/status
  verbs:
  - get
  - patch
  - update
