---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodelrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodelrequests/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodelrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodels/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.fga-operator
  resources:
  - authorizationmodels/status
  verbs:
  - get
  - patch
  - update
