---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - extensions.openfga-controller
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.openfga-controller
  resources:
  - stores/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.openfga-controller
  resources:
  - stores/status
  verbs:
  - get
  - patch
  - update
