apiVersion: extensions.openfga-controller/v1
kind: AuthorizationModelRequest
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: documents
spec:
  version: 1.1.3
  authorizationModel: |
    model
      schema 1.1
      
    type user
      
    type document
      relations
        define a: [user]
        define bar: [user]
        define reader: [user]
        define writer: [user]
        define owner: [user]
