networks:
  openfga-fga-operator:

services:
  postgres-fga-operator:
    image: postgres:14
    container_name: postgres-fga-operator
    networks:
      - openfga-fga-operator
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate-fga-operator:
    depends_on:
      postgres-fga-operator:
        condition: service_healthy
    image: openfga/openfga:v1.5
    container_name: migrate-fga-operator
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres-fga-operator:5432/postgres
    networks:
      - openfga-fga-operator

  openfga-fga-operator:
    depends_on:
      migrate-fga-operator:
        condition: service_completed_successfully
    image: openfga/openfga:v1.5
    container_name: openfga-fga-operator
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres-fga-operator:5432/postgres
      - OPENFGA_LOG_FORMAT=json
      - OPENFGA_AUTHN_METHOD=preshared
      - OPENFGA_AUTHN_PRESHARED_KEYS=foobar
    command: run
    networks:
      - openfga-fga-operator
    ports:
      # Needed for the http server
      - "8089:8080"
