apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-authorizationmodelrequest-editor-role
  labels:
  {{- include "openfga-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - extensions.openfga-controller
  resources:
  - authorizationmodelrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.openfga-controller
  resources:
  - authorizationmodelrequests/status
  verbs:
  - get