apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openfga-operator.fullname" . }}-authorizationmodelrequest-viewer-role
  labels:
  {{- include "openfga-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - extensions.openfga-controller
  resources:
  - authorizationmodelrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.openfga-controller
  resources:
  - authorizationmodelrequests/status
  verbs:
  - get